name: "Aggro CI"

on:
  - push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/amur-tiger/aggro:latest .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Image
        run: |
          docker push ghcr.io/amur-tiger/aggro:latest
